### ISSUE TITLE
DLPack tensor is not contiguous

### ISSUE THREAD

**Issue by zhukai242** [bug-developer021/YOLOV5_optimization_on_triton#1]
tritonclient.utils.InferenceServerException: [400] in ensemble 'simple_yolov5_ensemble', Failed to process the request(s) for model instance 'nms', message: TritonModelException: DLPack tensor is not contiguous. Only contiguous DLPack tensors that are stored in C-Order are supported

in /models/nms/1/model.py(58)

**Comment by bug-developer021** [comment]
[this post](https://forums.developer.nvidia.com/t/dlpack-tensor-is-not-contiguous-only-contiguous-dlpack-tensors-that-are-stored-in-c-order-are-supported/243362) may help you, or you can downgrade TritonServer version

**Comment by zhukai242** [comment]
@bug-developer021 thanks，it is really helpful, i have solve my problem.
